### ISSUE TITLE
Missing expires_in

### ISSUE THREAD

**Issue by narwy** [adonisjs/auth#137]
Reference to #134 

`expires_in` is missing from the response, this should not be inside the token and be at a top level to avoid applications spending time to decode the token.

RFC for OAuth2:
https://tools.ietf.org/html/rfc6749
RFC Appendix:
https://tools.ietf.org/html/rfc6749#appendix-A.14

**Comment by thetutlage** [comment]
The JWT scheme is not an implementation of OAuth2, so I will better ignore the spec.

However, I do have plans to replace it with fully fledged OAuth2 later

**Comment by narwy** [comment]
You open to a PR for full OAuth2?

**Comment by thetutlage** [comment]
Closing since not actionable. Regarding OAuth2, I don't have any plans as of now, until there is a huge demand in the community
