### ISSUE TITLE
Disable token encryptation

### ISSUE THREAD

**Issue by ghost** [adonisjs/auth#139]
My provider have a limitation, they use a 32 ASCII characters token, then the token that we send to the HTTP client must have 32 ASCII chars.

Possible solutions (I don't know which would be better)
- Disable token encryptation. Then the database stored token would be the same than Header token
- Put a middleware to encrypt HTTP header token before AdonisJS check it
- Implement a custom HTTP Auth token checker
- ...

**Comment by festuc** [comment]
Or put a middleware to decrypt HTTP header token before AdonisJS check it

**Comment by festuc** [comment]
I find a solution:

Create a middleware:
`
class EncryptHeader {
    /**
     * @param {object} ctx
     * @param {Request} ctx.request
     * @param {Function} next
     */
    async handle({ request }, next) {

        const token = request.header('Authorization').replace('Bearer ', '')
        request.request.headers.authorization = `Bearer ${Encryption.encrypt(token)}`

        // call next to advance the request
        await next()
    }
}
`

This Middleware encrypt the HTTP header token, then Adonis check it when is ecrypted.
It works, but us redundant. 

Are there a better solution?

**Comment by thetutlage** [comment]
Closing since not actionable
