### ISSUE TITLE
Users can see each other profiles!

### ISSUE THREAD

**Issue by agtabesh** [adonisjs/auth#141]
## Prerequisites
We have a website containing 200K users built on top of **Adonisjs 4.1.0** but recently we have figured out that users can access each other profiles! switching session driver from **file** to **redis** and vice versa does not help!

Does any one have faced with such problem?
What should we do to solve this critical problem?

## Package version
4.1.0

## Adonis-auth version
3.0.7

## Adonis-session version
1.0.28

## Node.js and npm version
10.17.0 and 6.11.3

**Comment by agtabesh** [comment]
I forgot to add **Adonis-auth** version which is **3.0.7**

**Comment by thetutlage** [comment]
@agtabesh The question is bit broad and impossible to provide any help without proper context or code.

Please provide

1. Which authentication scheme you are using?
2. Can you share the route definition on the route which is accessible by other users and which middleware are applied to that route?

**Comment by agtabesh** [comment]
@thetutlage I used `session` schema with `lucid` model
here are my codes:

## config/auth.js:
```javascript
session: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'session',
    uid: 'email',
    password: 'password'
}
```

## LoginController.js:
```javascript
async login ({ request, auth, session, response }) {
    const { email, password, remember, redirect } = request.all()
    try {
        let user = new User()
        user = await user.getUserByEmail(email)
        if (user) {
        if (Hash.verify(password, user.password, user.salt)) {
            await auth.remember(!!remember).loginViaId(user.id)
            if (session.get('_intended', false)) {
            const redirectUrl = session.get('_intended')
            session.forget('_intended')
            return response.redirect(redirectUrl)
            }
            if (redirect) {
            return response.redirect(redirect)
            }
            return response.route('/')
        }
        }
    } catch (e) {
        Logger.error(`Error in user login ${e.stack}`)
    }
    session
        .withErrors({ loginFailed: 'Wrong username or password!' })
        .flashExcept(['password'])
    return response.redirect(Route.url('login'))
}
```

and this Middleware is applied on routes:
```javascript
class Authenticated {
    async handle ({ request, response, auth, session }, next) {
        try {
            await auth.check()
        } catch (e) {
            session.put('_intended', request.url())
            return response.route('login')
        }
        await next()
    }
}
```

**Comment by RomainLanz** [comment]
Which is the route that are causing you issue?
How did you implement the authorization system?

**Comment by agtabesh** [comment]
@RomainLanz All route. There is a navbar in the app in which I show user first and last name. some users have reported that they see the others first and last name. yesterday, one of them tell us that there is an order in their panel that they have never by it!

My code is presented in previous post! do you need anything else?

**Comment by thetutlage** [comment]
> There is a navbar in the app in which I show user first and last name
How do you fetch this first and last name?

**Comment by thetutlage** [comment]
It will be nice, if you can invite one of us to have access to the codebase and share steps on how to get that codebase running.

**Comment by agtabesh** [comment]
> > There is a navbar in the app in which I show user first and last name
> 
> How do you fetch this first and last name?

Actually, first and last name are two property of each user.


> It will be nice, if you can invite one of us to have access to the codebase and share steps on how to get that codebase running.

It does not happen to all users but 2-3 of them! Through, I don't have any hope to find the problem by checking step by step of codebase! However, If you need the source codes, I can give you for further assessment!

**Comment by agtabesh** [comment]
Any help?

**Comment by thetutlage** [comment]
@agtabesh Can you invite me to the repo, so that I can go through the source code. Please share some concrete steps on how to get up and running with the code

**Comment by thetutlage** [comment]
Closing since not actionable
