### ISSUE TITLE
Passing user id as number to auth.attempt throws an error

### ISSUE THREAD

**Issue by CodingDive** [adonisjs/auth#143]
Even though my primary key is a `bigInt`, I can't pass a number to `auth.attempt`

## Package version
```
"@adonisjs/auth": "^3.0.7",
"@adonisjs/framework": "^5.0.13",
```

## Node.js and npm version
```
node 12.9.1
npm 6.10.2
```

## Sample Code (to reproduce the issue)
`auth.attempt(Number(userId), validPassword)` will throw an error.

`auth.attempt(userId.toString(), validPassword)` works fine.

## BONUS
I traced the bug to this line which always wants the user id to be a string. https://github.com/adonisjs/adonis-auth/blob/56621d0aa2/src/Schemes/Base.js#L187

**Comment by thetutlage** [comment]
Yeah, looks like a clear bug

**Comment by CodingDive** [comment]
@thetutlage is this already fixed in v5 or should we keep it open?

**Comment by thetutlage** [comment]
Already fixed for v5
