### ISSUE TITLE
bcrypt doesn't support $2b$ prefix

### ISSUE THREAD

**Issue by anthonmanix** [adonisjs/auth#144]
I have an existing user table with bcrypt hashed passwords. When I try `auth.atempt` I get an error `incompatible 2b identifier found in the hash`. I tried comparing with the `bcrypt` package directly and it validates.

I saw you have this issue open at [@phc/bcrypt](https://github.com/simonepri/phc-bcrypt/issues/26). Maybe it's related?

## Package version
```
"@adonisjs/auth": "^4.1.4",
"@adonisjs/core": "^5.0.0-preview-rc-1.5",
```

## Node.js and npm version
```
node v14.0.0
npm 6.14.4
```

## Sample Code (to reproduce the issue)
```
auth.atempt(email, password)
```

**Comment by thetutlage** [comment]
Does it mean, you want to verify the password hashed by another library using the `Hash` module of AdonisJS?

We use [PHC String formatting](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md) and hence password must be hashed in the same format

**Comment by anthonmanix** [comment]
I guess. I was using bcrypt directly before. I forgo the attempt method and use login, but it doesn't feel clean to have a separate bycript import.

Maybe there could be a flag for checking other formats, while using PHC for new users?

**Comment by thetutlage** [comment]
Were you using the Adonis hash module earlier or is it a seperate project that you are planning to migrate over to AdonisJS?

**Comment by anthonmanix** [comment]
A separate project I want to migrate to adonis. I really like the framework and docs. Good job. And thank you for the quick replies.

**Comment by anthonmanix** [comment]
I checked my Adonis 4 project and the passwords there have $2a$ prefix. Maybe there could be an issue when migrating from 4 to 5 also.

**Comment by thetutlage** [comment]
Yeah, we will have a migration process for migration v4 passwords. But, I don't think, an option for all sort of migration can be supported. For example: Someone may have an app that is using a different algorithm all together.

What you can do instead is setup your own driver. Here is a gist showing how to do it https://gist.github.com/thetutlage/cf32e18d66408fd96fc8b7d3591c7a1a

- You create a new file `start/hashDriver.ts` and define your driver inside it and then register the driver using `Hash.extend` method.
- Next register this file inside `.adonisrc.json` under `preloads` array. So that AdonisJS loads it automatically for you.
- The above steps takes care of runtime, but we need to satisfy Typescript compiler as well. So open `contracts/auth.ts` file and replace its contents from the one inside the gist.
- Finally, open the `config/hash.ts` and now define the config for your driver.

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by amraei** [comment]
@thetutlage Where can I find any guides about migrating passwords from Adonis v4 to v5?

**Comment by danegigi** [comment]
I'm creating a new system that is linked to an old database that was used by an old webiste built on laravel 5.8. The hashed password starts with $2y and $2a  and when I try to login using bcrypt I'm getting **Incompatible 2a identifier found in the hash** or **Incompatible 2y identifyer found in the hash**. Is there a way for Adonis 5 to authenticate user using the password saved in the database?

**Comment by thetutlage** [comment]
Just create a custom driver for the same. Here are the docs for the same https://docs.adonisjs.com/guides/security/hashing#adding-a-custom-driver

**Comment by thetutlage** [comment]
@amraei Here is an article on the same https://bitkidd.dev/posts/migrate-adonisjs-v4-user-passwords-to-v5

**Comment by amitappaspect** [comment]
@anthonmanix I got the same situation I was using database that connected with Laravel. so I just extend Hash functionality with a custom driver.

create a file index.ts under providers/HashDriver and put below code.

```ts
import { HashDriverContract } from '@ioc:Adonis/Core/Hash'
const bcrypt = require('bcrypt');

const saltRounds = 10;

export class LaravelHash implements HashDriverContract {
    public async make(value: string) {
      const _hashedValue = bcrypt.hashSync(value, saltRounds);
        return _hashedValue;
    }

    public async verify(hashedValue: string, plainValue: string) {
        let newHash: string;
        if (hashedValue.includes('$2y$10$')) {
            newHash = hashedValue.replace("$2y$10$", "$2a$10$");
        } else {
            newHash = hashedValue;
        }
        return await bcrypt.compareSync(plainValue, newHash);
    }
}
```
Now add below code in 'boot' method of AppProvider.ts
```ts
const { LaravelHash } = await import('./HashDriver')
    const Hash = this.app.container.use('Adonis/Core/Hash')

    Hash.extend('laravelhash', () => {
      return new LaravelHash()
    })
```

Now add this drive to config file under config/hash.ts and make it default.

```ts
laravelhash: {
      driver: 'laravelhash',
      rounds: 10,
    }
```

Hope it will solve your issue.

**Comment by AbidKhairyAK** [comment]
modified version of @amitappaspect code for adonis js v6.

 1. create new file on `/driver/LaravelHashDriver.ts`

```ts
import {
  HashDriverContract,
  ManagerDriverFactory
} from '@adonisjs/core/types/hash'

/**
 * need to polyfill the require function
 */
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const bcrypt = require('bcrypt');


const previousAlgorithm = '$2y$12$' // bcrypt algorithm from the few characters on the start of the previously encrypted password
const currentAlgorithm  = '$2b$12$' // this is for the current encrypted password
const saltRounds        = 12        // match the salt rounds of the previous algorithm, it's on the second $ sign


export class LaravelHashDriver implements HashDriverContract {


  /**
   * Convert raw value to Hash, 
   * used when creating new password for user
   */
  async make(value: string): Promise<string> {
    const _hashedValue = bcrypt.hashSync(value, saltRounds);
    return _hashedValue;
  }

  /**
   * Verify if the plain value matches the provided hash, 
   * used on login
   */
  async verify( hashedValue: string, plainValue: string ): Promise<boolean> {
    let currentHash = hashedValue;

    if (hashedValue.includes(previousAlgorithm)) {
        currentHash = hashedValue.replace(previousAlgorithm, currentAlgorithm);
    }

    return await bcrypt.compareSync(plainValue, currentHash);
  }

  /**
   * idk the logic for this, so i just put it to default value
   */
  needsReHash(): boolean {
    return false;
  }
  isValidHash(): boolean {
    return true
  }
}

/**
 * Factory function so you dont need to intiate it before using it
 */
export function LaravelHashFunction (): ManagerDriverFactory {
  return () => {
    return new LaravelHashDriver()
  }
}
``` 


2. modify your `/config/hash.ts`

```ts
import { LaravelHashFunction } from '../driver/LaravelHashDriver.js'

// ... other code ...

const hashConfig = defineConfig({
  default: 'laravel_hash',

  list: {
    laravel_hash: LaravelHashFunction()
  },
})

// ... other code ...
```


3. IF you are authenticating using auth finder, then update your `/app/models/user.ts` too

```ts
const AuthFinder = withAuthFinder(() => hash.use('laravel_hash'), {
  uids: ['email'],
  passwordColumnName: 'password',
})
```
