### ISSUE TITLE
Template containing mixed tabs and spaces causing linting errors

### ISSUE THREAD

**Issue by allanmaral** [adonisjs/auth#149]
## Package version
Adonis: 5.0.0-preview-rc
Auth: 4.3.1

## Node.js and npm version
12.18.3

## Sample Code (to reproduce the issue)
https://github.com/adonisjs/auth/blob/0d64cf018046d45b98e4c4f2fc708c9944eccedc/templates/middleware/Auth.txt#L26-L35

https://github.com/adonisjs/auth/blob/0d64cf018046d45b98e4c4f2fc708c9944eccedc/templates/config/partials/basic-guard.txt#L1-L19

https://github.com/adonisjs/auth/blob/0d64cf018046d45b98e4c4f2fc708c9944eccedc/templates/contract/partials/basic-guard.txt#L1-L13

Not really a bug, just the templates mixing tabs with spaces and causing the linter to show `Mixed spaces and tabs. eslint(no-mixed-spaces-and-tabs)` errors.

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
