### ISSUE TITLE
Auth views scaffold

### ISSUE THREAD

**Issue by rickavmaniac** [adonisjs/auth#164]
I just use the @adonisjs/auth module for the first time. Everything is great but is there a reason why adonis do not scaffold a default route, controller and views to support the web auth? In Rails and in Laravel we do have this kind of helper. It is good and essential for fast prototyping and also very good for newbie to learn the pattern.

It is something that they don't want at all or it is just a matter to taking the time someday to do it? If it is the latter maybe I can do a PR and contribute

**Comment by thetutlage** [comment]
Yes. This is an intentional decision. We do not ship with views, controllers or routes from the official packages. This is its own upsides and downsides at the same time.

Also, this opens up the possibility for the ecosystem to create more opinionated packages

**Comment by rickavmaniac** [comment]
Ok thanks for taking time to explained your position.
