### ISSUE TITLE
Switch database connection before auth.attempt

### ISSUE THREAD

**Issue by swapnilnandgave** [adonisjs/auth#170]
How do i set db connection name while auth.attempt?

we have changing database connection on the fly as per request using Database.connection but while trying do auth.attempt then it uses default connection which is set in env

Is there any way to set connection before auth.attempt?

**Comment by swapnilnandgave** [comment]
Default connection is working as expected but I want to switch db connection before `auth.attempt`
Can somebody help me with this? It is bit urgent.I have tried below but nothing works. 

First tried this
`User.connection = connectionName` - doesn't work

Then
`ctx.auth.config.provider.connection = connectionName` - doesn't work

Then
`user.useConnection(connectionName)` - doesn't work

Then in User.ts
`static get connection () {
    return 'mssql4';
  }` - doesn't work


Nothing works for me. Anything missing over here

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
