### ISSUE TITLE
How to create custom authentication?

### ISSUE THREAD

**Issue by alex-oliveira** [adonisjs/auth#172]
I am trying to create a customized "provider / guard" to enable user authentication.

I plan to use JWT and a no-SQL database (DynamoDB or FaunaDB), but I am not finding more detailed information on how to do this.

I would like this implementation to be integrated with the way AdonisJs works.

Could someone get me some reference?

**Comment by RomainLanz** [comment]
Hey @alex-oliveira! 👋 

Since this is not an issue with the framework but a question on how you can implement something, please create a discussion thread inside our [forum](https://github.com/adonisjs/core/discussions).

**Comment by thetutlage** [comment]
I have written the docs for adding a custom user provider for auth here. https://docs.adonisjs.com/guides/auth/custom-user-provider. Here is an example project showcasing it with Mongoose https://github.com/adonisjs-community/auth-mongoose-provider.

The docs for **custom guard** are yet to come
