### ISSUE TITLE
Separate auth for admin, user models in version 5

### ISSUE THREAD

**Issue by kaushikabhi999** [adonisjs/auth#173]
How can we achieve this in version 5? @thetutlage 

https://github.com/adonisjs/auth/issues/121

**Comment by RomainLanz** [comment]
Hey @kaushikabhi999! 👋 


This is more a question than an issue with the framework itself.
Since we want to keep this space clean, please use [GitHub Discussion](https://github.com/adonisjs/core/discussions) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
