### ISSUE TITLE
How to use JWT?

### ISSUE THREAD

**Issue by ibalaji777** [adonisjs/auth#176]
I cannot see jwt in New docs ,I need to implement.

**Comment by RomainLanz** [comment]
Hey @ibalaji777! 👋 

This is more a question than an issue with the framework itself.
Since we want to keep this space clean, please use [GitHub Discussion](https://github.com/adonisjs/core/discussions) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
