### ISSUE TITLE
Separated auth for admin, user models

### ISSUE THREAD

**Issue by tiagocdr** [adonisjs/auth#177]
Separated auth for admin, user models #121 Referencing this question in the past, how do you go about doing this nowadays with the new adonis5 ts app? I've gone trough the documentation and it instructs to add a new provider inside the Providers and same with the GuardsList inside 'contracts/auth.ts' but it doesn't go any further than that. Thanks in advance!

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**

**Comment by tiagocdr** [comment]
Ok I understand sorry about that.
