### ISSUE TITLE
plans to start implementing ldap on adonis?

### ISSUE THREAD

**Issue by Kledenai** [adonisjs/auth#178]
I'm working with adonis on big projects and the company always asks about the ldap integration because they basically use it in most of their solutions

**Comment by thetutlage** [comment]
Since, I don't work with Ldap everyday, it is hard for me to create something around it. Maybe, you can take an initiative and create an ecosystem package? I can surely answer questions around extending auth or creating a package in general :)

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
