### ISSUE TITLE
There is some out of the box way to implement refresh token for API?

### ISSUE THREAD

**Issue by RaphaelBatagini** [adonisjs/auth#182]
In AdonisJS v4, I was able to add refresh token to my authentication action as described [here](https://legacy.adonisjs.com/docs/4.1/authentication#_withrefreshtoken).

Now, using AdonisJS v5, I am unable to find something related to this in the documentation.
Something like this "withRefreshToken" exists in v5? Any lead about how can I proceed? (using API auth)

**Comment by thetutlage** [comment]
Explained here https://github.com/adonisjs/core/discussions/2039#discussioncomment-201869
