### ISSUE TITLE
[V5]custom the default auth target tables/model

### ISSUE THREAD

**Issue by dirszas14** [adonisjs/auth#183]
is there any way to change the default target other that User model?
i've seen you can only set model User only.

**config/auth.ts**
![image](https://user-images.githubusercontent.com/31124351/136497290-ccbfa639-b95f-4258-81d0-de50692f1b80.png)

**contracts/auth.ts**
![image](https://user-images.githubusercontent.com/31124351/136497366-87ff0e49-ec2a-4fb8-afc9-96e4ea5af6cd.png)

I made this 2 tables because every users has different feature so I separately.
I did this on Laravel works as well.

**Comment by thetutlage** [comment]
Closing since not actionable.
