### ISSUE TITLE
OAT Verify current time against expiresAt field for authentication

### ISSUE THREAD

**Issue by AlanNeads** [adonisjs/auth#185]
https://github.com/adonisjs/auth/blob/08c0e33b4250ee6e61625eb09a64b11e347eec91/src/Guards/Oat/index.ts#L360

~~Would be handy to also check the expiresAt field against the current time to ensure the token hasn't expired.~~

Resolved it myself, I'm a big dumb dumb. On another note with it working correctly it would perhaps be nice to have the ability to assign a callback to optionally prune the token storage/db

**Comment by thetutlage** [comment]
Its already validated. https://github.com/adonisjs/auth/blob/08c0e33b4250ee6e61625eb09a64b11e347eec91/src/TokenProviders/Database/index.ts#L107-L113
