### ISSUE TITLE
Support custom token provider with documentation and example

### ISSUE THREAD

**Issue by buzzware** [adonisjs/auth#199]
## Why this feature is required (specific use-cases will be appreciated)?

Just as the process for providing a custom user provider is documented here https://docs.adonisjs.com/guides/auth/custom-user-provider
there are many authentication servers such as Firebase Auth and IdentityServer that could be integrated with a custom token provider, but Adonis seems to only support either database or redis TokenProviders.

## Have you tried any other work arounds?

Not yet

## Are you willing to work on it with little guidance?

Yes

**Comment by thetutlage** [comment]
It will require some internal architecture changes. Lemme see if I can pick it up in coming days

**Comment by geoguide** [comment]
Would this include auth0 token provider functionality? I've been banging against this and it's prevented my project from moving forward. It'd be nice to figure out if we could leverage passport to handle it somehow.

**Comment by fzhnf** [comment]
hello, im new here, and kinda stuck with integrating firebase Auth, and keep circling around seeking tutorial/guide but keep getting deprecated version or abandoned issue, i just need to know how
