### ISSUE TITLE
Why my token from auth "memberjwt" valid on middleware "jwt" auth ?

### ISSUE THREAD

**Issue by anggi117** [adonisjs/auth#203]
I have 2 auth JWT (jwt and memberjwt)
![image](https://user-images.githubusercontent.com/42998655/180148287-7a67ed2c-fc2d-42fc-b546-7b77b8592cb6.png)

and im already set the middleware to "jwt" in route.
![image](https://user-images.githubusercontent.com/42998655/180148362-ec7e3d56-ca8f-4cf2-836c-de557d64e64c.png)

but why my token generate from "memberjwt" auth valid on auth "jwt" ?

is there any solution?

this my route using auth "memberjwt" and email its : kotnol@gmail.com
![image](https://user-images.githubusercontent.com/42998655/180149059-d2b164b1-1a00-4831-81bf-baae3d6c4507.png)

but im check it using auth.getuser() its still showing with different data, even though that token from memberjwt
![image](https://user-images.githubusercontent.com/42998655/180149237-9210b2a2-2090-4d52-97a3-2ab618b0d5bf.png)

i want that token from "memberjwt" auth its invalid in "jwt" auth

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
