### ISSUE TITLE
JWT support

### ISSUE THREAD

**Issue by hichemfantar** [adonisjs/auth#207]
## Why this feature is required (specific use-cases will be appreciated)?
JWT authentication is a very common method of authentication especially on mobile applications.

## Have you tried any other work arounds?
There's a [third party package](https://github.com/maxgalbu/adonis5-jwt) but I'd prefer a first party solution like Laravel Sanctum. I noticed that jwt auth was available in v4 but for some reason it's gone in v5.

## Are you willing to work on it with little guidance?
Will try my best. But I'm still not familiar with the codebase.

**Comment by RomainLanz** [comment]
Hey @hichemfantar! 👋🏻 

What's wrong to use OAT Token instead of JWT in your case?

**Comment by hichemfantar** [comment]
I appear mistaken in that laravel sanctum's solution isn't exactly like JWT but It provides similar functionality. I assume I'm supposed to simply use [API tokens](https://docs.adonisjs.com/guides/auth/api-tokens-guard) for my mobile application?
What do you mean exactly by OAT Token?

**Comment by RomainLanz** [comment]
Yes, OAT ([API Tokens](https://docs.adonisjs.com/guides/auth/api-tokens-guard)) should work for your use case. 👍🏻

**Comment by hichemfantar** [comment]
Great, I'm closing this then.
