### ISSUE TITLE
Auth module strictly depends on Lucid

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/auth#236]
Hey there! 👋🏻 

The `@adonisj/auth` module strictly depends on `@adonisjs/lucid` since we added the `withAuthFinder` mixins.

The mixin imports a Lucid decorator at its root:

```ts
import { beforeSave, type BaseModel } from '@adonisjs/lucid/orm'
```

Since we are exporting the mixin from the root of the package, we strictly depend on it and cannot use the Auth module without installing Lucid.

```ts
// index.ts
export { withAuthFinder } from './src/mixins/with_auth_finder.js'
```

We must find a way to remove this hard dependency without adding any breaking change to the current API.

**Comment by Julien-R44** [comment]
I would suggest trying something like this : 

```ts
// utils.ts
export function isModuleInstalled(moduleName: string) {
  const require = createRequire(import.meta.url)
  try {
    require.resolve(moduleName)
    return true
  } catch (error) {
    return false
  }
}

// index.ts of @adonisjs/auth
let withAuthFindder
if (isModuleInstalled('@adonisjs/lucid')) {
  withAuthFinder = await import('./with_auth_finder')
}

export { withAuthFinder }
```

this should work fine

**Comment by targos** [comment]
Can't use `import.meta.resolve`?

**Comment by thetutlage** [comment]
Should we implement the suggestion shared by @Julien-R44 or have a breaking change release that moves the import to a sub-module?

```ts
import { withAuthFinder } from '@adonisjs/auth/mixins'
```

**Comment by RomainLanz** [comment]
> Should we implement the suggestion shared by @Julien-R44 or have a breaking change release that moves the import to a sub-module?
> 
> ```ts
> import { withAuthFinder } from '@adonisjs/auth/mixins'
> ```

It feels better to have the `withAuthFinder` method in its own sub-module, but  I believe we can implement @Julien-R44's suggestion to avoid a breaking change.

However, we keep in mind that this needs to be done in the next major release.

**Comment by Julien-R44** [comment]
i agree a breaking change just for that would be a bit annoying

I would say : 
- lets re-export `withAuthFinder` from the `mixins` submodule right now
- lets also annotate the `withAuthFinder` exported from the root module with `deprecated` tag

**Comment by thetutlage** [comment]
Released. https://github.com/adonisjs/auth/releases/tag/v9.2.0

**Comment by markgidman-rad** [comment]
In case anyone comes here later, assuming you are using lucid, to adopt this change simply update

`import { withAuthFinder } from '@adonisjs/auth'`
to 
`import { withAuthFinder } from '@adonisjs/auth/mixins/lucid'`
