### ISSUE TITLE
`returning` is not supported by mysql

### ISSUE THREAD

**Issue by sooluh** [adonisjs/auth#241]
### Package version

9.1.1

### Describe the bug

I saw the following 2 codes here,

https://github.com/adonisjs/auth/blob/016cc8c6a27109597d86c37caa81a5cf793f529a/modules/access_tokens_guard/token_providers/db.ts#L175-L176

https://github.com/adonisjs/auth/blob/016cc8c6a27109597d86c37caa81a5cf793f529a/modules/session_guard/token_providers/db.ts#L145-L146

It is noticed that the method/function `returning('id')` is used there, which is not supported for MySQL by knex itself [^1][^2]. I know this is for returning an "identifier", but in the previous version (for Adonis v5), there was no identifier and it worked fine.

Is there a fix for this?

[^1]: https://knexjs.org/guide/query-builder.html#returning
[^2]: https://github.com/knex/knex/issues/2075

**Comment by thetutlage** [comment]
Hey, it this a MySQL 5.7 related issue? Because we have tests running for MySQL 8 and everything seems to be fine.

**Comment by sooluh** [comment]
The version of MySQL I'm using (more precisely, I'm using MariaDB).

```
mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

And I tried the RETURNING query myself and it worked. Honestly, I don't know which part isn't supported, but I've seen documentation and issues related to Knex regarding this matter (as per footnotes).

![returning query](https://github.com/adonisjs/auth/assets/20874779/f728abac-7f97-4e29-b303-2e3af6a8e32e)

**Comment by thetutlage** [comment]
I am not able to reproduce it. I will recommend creating a failing test in this repo and then I can look into pushing a fix.

**Comment by sooluh** [comment]
I found the issue, @thetutlage! It's because I used UUID (`char(36)`) on the `access_auth_tokens` table. I switched it to `bigint` and it's working fine now. Hopefully UUID will be supported here.

**Comment by sooluh** [comment]
Can I reopen the issue here and rename the title to "UUID support in foreign keys"?
