### ISSUE TITLE
guardFactory is not a function

### ISSUE THREAD

**Issue by AimForNaN** [adonisjs/auth#242]
### Package version

@adonisjs/auth@9.1.1

### Describe the bug

Setting guards to middleware.auth() throws an error.

Code that triggered it:
```js
router.get('/', '#controllers/index_controller.index').use(middleware.auth({
	guards: ['web', 'api'],
}));
```

Error blamed on `app/middleware/auth_middleware.ts` line 22.

**Comment by thetutlage** [comment]
Please share complete reproduction. Just with one line of code, I cannot figure out the error.
